# Generated by Django 5.2 on 2025-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_session_id_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Session', max_length=100),
        ),
    ]
