# Generated by Django 5.2 on 2025-05-26 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_session_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(related_name='sessions_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
