# Generated by Django 5.2 on 2025-05-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_participants'),
    ]

    operations = [
    ]
