# Generated by Django 5.2 on 2025-05-26 10:45

from django.db import migrations, models

def generate_uuid(apps, schema_editor):
    import uuid
    Session = apps.get_model('core', 'Session')
    for session in Session.objects.all():
        session.uuid = uuid.uuid4()
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_session_uuid_alter_session_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=False),
        ),
        migrations.RunPython(generate_uuid, migrations.RunPython.noop),
    ]
