# Generated by Django 5.2 on 2025-05-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_session_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='uuid',
        ),
    ]
