# Generated by Django 5.2 on 2025-05-26 12:22

from django.db import migrations

def set_creator_to_user1(apps, schema_editor):
    Session = apps.get_model('core', 'Session')
    for session in Session.objects.filter(creator__isnull=True):
        session.creator = session.user1  # Assuming user1 should be the creator
        session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_session_uuid_alter_session_creator'),
    ]

    operations = [
        migrations.RunPython(set_creator_to_user1, migrations.RunPython.noop),
    ]
