# Generated by Django 5.2 on 2025-05-26 12:32

from django.db import migrations

"""
    Replicates what I did in shell:
    - Adds user1 and user2 to participants
"""
def add_user1_and_user2_to_participants(apps, schema_editor):
    Session = apps.get_model('core', 'Session')
    for session in Session.objects.all():
        # Add user1 and user2 to participants (if not already present)
        if not session.participants.filter(id=session.user1.id).exists():
            session.participants.add(session.user1)
        if not session.participants.filter(id=session.user2.id).exists():
            session.participants.add(session.user2)
        session.save()

def verify_population(apps, schema_editor):
    Session = apps.get_model('core', 'Session')
    problematic = Session.objects.filter(participants__isnull=True)
    if problematic.exists():
        print(f"Warning: {problematic.count()} sessions still have no participants")
        for session in problematic:
            print(f"Session ID: {session.id}, Creator: {session.creator.username if session.creator else 'None'}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_populate_creator'),
    ]

    operations = [
        migrations.RunPython(add_user1_and_user2_to_participants, migrations.RunPython.noop),
        migrations.RunPython(verify_population, migrations.RunPython.noop),
    ]
