# Generated by Django 5.2 on 2025-05-26 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_session_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(null=True, editable=False, unique=False),
        ),
    ]
