# Generated by Django 5.2 on 2025-05-26 13:06

import uuid
from django.db import migrations

def populate_uuid(apps, schema_editor):
    Session = apps.get_model('core', 'Session')
    for session in Session.objects.filter(uuid__isnull=True):
        session.uuid = uuid.uuid4()
        session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_session_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
    ]
