# Generated by Django 5.2 on 2025-05-26 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
