# Generated by Django 5.2 on 2025-05-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_session_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user2',
        ),
    ]
