# Generated by Django 5.2 on 2026-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_session_user1_remove_session_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='theme_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
